log:
  level: info
  syslog: [syslog ip/dns]
  file: [path of destination log file]
mqtt:
  broker: [mqtt ip/dns]
  qos: 0
  port: 1883
  retain: True
  authentication: False
  user: 
  password: 
  tls_enabled: False
  tls_ca_cert: 
  tls_cert:
  tls_key:
  tls_insecure: True
  tls_version: ssl.PROTOCOL_TLSv1_2
  client_id: dsmr2mqtt
  topic_prefix: zigbee2mqtt/dsmr
serial:
  baudrate: 115200
  port: /dev/ttyDSMR
